version: 2
jobs:
  prepare_deploy:
    docker:
      - image: eklhad/terrasnek-circleci:0.2
    working_directory: ~/terrasnek
    steps:
      - checkout
      - run:
          name: Lint the code, build the docs, run a full test suite and the contributor check.
          command: |
            make lint
            make docs
            make coverage
            make contributor_check
workflows:
  version: 2
  test_and_deploy:
    jobs:
      - prepare_deploy